//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietOCR {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class BulkDialog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
     
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VietOCR.BulkDialog", typeof(BulkDialog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode btnInput_ImeMode {
            get {
                object obj = ResourceManager.GetObject("btnInput.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=365,Y=23}.
        /// </summary>
        public static System.Drawing.Point btnInput_Location {
            get {
                object obj = ResourceManager.GetObject("btnInput.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        public static System.Windows.Forms.Padding btnInput_Margin {
            get {
                object obj = ResourceManager.GetObject("btnInput.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=40, Height=28}.
        /// </summary>
        public static System.Drawing.Size btnInput_Size {
            get {
                object obj = ResourceManager.GetObject("btnInput.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 16.
        /// </summary>
        public static int btnInput_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnInput.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string btnInput_Text {
            get {
                return ResourceManager.GetString("btnInput.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string btnInput_ToolTip {
            get {
                return ResourceManager.GetString("btnInput.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode btnOutput_ImeMode {
            get {
                object obj = ResourceManager.GetObject("btnOutput.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=365,Y=55}.
        /// </summary>
        public static System.Drawing.Point btnOutput_Location {
            get {
                object obj = ResourceManager.GetObject("btnOutput.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        public static System.Windows.Forms.Padding btnOutput_Margin {
            get {
                object obj = ResourceManager.GetObject("btnOutput.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=40, Height=28}.
        /// </summary>
        public static System.Drawing.Size btnOutput_Size {
            get {
                object obj = ResourceManager.GetObject("btnOutput.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 17.
        /// </summary>
        public static int btnOutput_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnOutput.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string btnOutput_Text {
            get {
                return ResourceManager.GetString("btnOutput.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string btnOutput_ToolTip {
            get {
                return ResourceManager.GetString("btnOutput.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode buttonCancel_ImeMode {
            get {
                object obj = ResourceManager.GetObject("buttonCancel.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=305,Y=105}.
        /// </summary>
        public static System.Drawing.Point buttonCancel_Location {
            get {
                object obj = ResourceManager.GetObject("buttonCancel.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        public static System.Windows.Forms.Padding buttonCancel_Margin {
            get {
                object obj = ResourceManager.GetObject("buttonCancel.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=100, Height=28}.
        /// </summary>
        public static System.Drawing.Size buttonCancel_Size {
            get {
                object obj = ResourceManager.GetObject("buttonCancel.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 21.
        /// </summary>
        public static int buttonCancel_TabIndex {
            get {
                object obj = ResourceManager.GetObject("buttonCancel.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string buttonCancel_Text {
            get {
                return ResourceManager.GetString("buttonCancel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string buttonCancel_ToolTip {
            get {
                return ResourceManager.GetString("buttonCancel.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode buttonRun_ImeMode {
            get {
                object obj = ResourceManager.GetObject("buttonRun.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=197,Y=105}.
        /// </summary>
        public static System.Drawing.Point buttonRun_Location {
            get {
                object obj = ResourceManager.GetObject("buttonRun.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        public static System.Windows.Forms.Padding buttonRun_Margin {
            get {
                object obj = ResourceManager.GetObject("buttonRun.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=100, Height=28}.
        /// </summary>
        public static System.Drawing.Size buttonRun_Size {
            get {
                object obj = ResourceManager.GetObject("buttonRun.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 20.
        /// </summary>
        public static int buttonRun_TabIndex {
            get {
                object obj = ResourceManager.GetObject("buttonRun.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string buttonRun_Text {
            get {
                return ResourceManager.GetString("buttonRun.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string buttonRun_ToolTip {
            get {
                return ResourceManager.GetString("buttonRun.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text.
        /// </summary>
        public static string comboBoxOutputFormat_Items {
            get {
                return ResourceManager.GetString("comboBoxOutputFormat.Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text+.
        /// </summary>
        public static string comboBoxOutputFormat_Items1 {
            get {
                return ResourceManager.GetString("comboBoxOutputFormat.Items1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hocr.
        /// </summary>
        public static string comboBoxOutputFormat_Items2 {
            get {
                return ResourceManager.GetString("comboBoxOutputFormat.Items2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=115,Y=105}.
        /// </summary>
        public static System.Drawing.Point comboBoxOutputFormat_Location {
            get {
                object obj = ResourceManager.GetObject("comboBoxOutputFormat.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        public static System.Windows.Forms.Padding comboBoxOutputFormat_Margin {
            get {
                object obj = ResourceManager.GetObject("comboBoxOutputFormat.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=64, Height=24}.
        /// </summary>
        public static System.Drawing.Size comboBoxOutputFormat_Size {
            get {
                object obj = ResourceManager.GetObject("comboBoxOutputFormat.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 23.
        /// </summary>
        public static int comboBoxOutputFormat_TabIndex {
            get {
                object obj = ResourceManager.GetObject("comboBoxOutputFormat.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string comboBoxOutputFormat_ToolTip {
            get {
                return ResourceManager.GetString("comboBoxOutputFormat.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=17}.
        /// </summary>
        public static System.Drawing.Point folderBrowserDialog1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("folderBrowserDialog1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool labelInput_AutoSize {
            get {
                object obj = ResourceManager.GetObject("labelInput.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode labelInput_ImeMode {
            get {
                object obj = ResourceManager.GetObject("labelInput.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=15,Y=30}.
        /// </summary>
        public static System.Drawing.Point labelInput_Location {
            get {
                object obj = ResourceManager.GetObject("labelInput.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=0,Right=4,Bottom=0}.
        /// </summary>
        public static System.Windows.Forms.Padding labelInput_Margin {
            get {
                object obj = ResourceManager.GetObject("labelInput.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=87, Height=17}.
        /// </summary>
        public static System.Drawing.Size labelInput_Size {
            get {
                object obj = ResourceManager.GetObject("labelInput.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 18.
        /// </summary>
        public static int labelInput_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelInput.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Folder:.
        /// </summary>
        public static string labelInput_Text {
            get {
                return ResourceManager.GetString("labelInput.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string labelInput_ToolTip {
            get {
                return ResourceManager.GetString("labelInput.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool labelOutput_AutoSize {
            get {
                object obj = ResourceManager.GetObject("labelOutput.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode labelOutput_ImeMode {
            get {
                object obj = ResourceManager.GetObject("labelOutput.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=15,Y=62}.
        /// </summary>
        public static System.Drawing.Point labelOutput_Location {
            get {
                object obj = ResourceManager.GetObject("labelOutput.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=0,Right=4,Bottom=0}.
        /// </summary>
        public static System.Windows.Forms.Padding labelOutput_Margin {
            get {
                object obj = ResourceManager.GetObject("labelOutput.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=99, Height=17}.
        /// </summary>
        public static System.Drawing.Size labelOutput_Size {
            get {
                object obj = ResourceManager.GetObject("labelOutput.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 19.
        /// </summary>
        public static int labelOutput_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelOutput.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Folder:.
        /// </summary>
        public static string labelOutput_Text {
            get {
                return ResourceManager.GetString("labelOutput.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string labelOutput_ToolTip {
            get {
                return ResourceManager.GetString("labelOutput.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool labelOutputFormat_AutoSize {
            get {
                object obj = ResourceManager.GetObject("labelOutputFormat.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=16,Y=108}.
        /// </summary>
        public static System.Drawing.Point labelOutputFormat_Location {
            get {
                object obj = ResourceManager.GetObject("labelOutputFormat.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=0,Right=4,Bottom=0}.
        /// </summary>
        public static System.Windows.Forms.Padding labelOutputFormat_Margin {
            get {
                object obj = ResourceManager.GetObject("labelOutputFormat.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=99, Height=17}.
        /// </summary>
        public static System.Drawing.Size labelOutputFormat_Size {
            get {
                object obj = ResourceManager.GetObject("labelOutputFormat.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 24.
        /// </summary>
        public static int labelOutputFormat_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelOutputFormat.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Format.
        /// </summary>
        public static string labelOutputFormat_Text {
            get {
                return ResourceManager.GetString("labelOutputFormat.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string labelOutputFormat_ToolTip {
            get {
                return ResourceManager.GetString("labelOutputFormat.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=115,Y=26}.
        /// </summary>
        public static System.Drawing.Point textBoxInput_Location {
            get {
                object obj = ResourceManager.GetObject("textBoxInput.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        public static System.Windows.Forms.Padding textBoxInput_Margin {
            get {
                object obj = ResourceManager.GetObject("textBoxInput.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=241, Height=22}.
        /// </summary>
        public static System.Drawing.Size textBoxInput_Size {
            get {
                object obj = ResourceManager.GetObject("textBoxInput.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 14.
        /// </summary>
        public static int textBoxInput_TabIndex {
            get {
                object obj = ResourceManager.GetObject("textBoxInput.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string textBoxInput_ToolTip {
            get {
                return ResourceManager.GetString("textBoxInput.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=115,Y=58}.
        /// </summary>
        public static System.Drawing.Point textBoxOutput_Location {
            get {
                object obj = ResourceManager.GetObject("textBoxOutput.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        public static System.Windows.Forms.Padding textBoxOutput_Margin {
            get {
                object obj = ResourceManager.GetObject("textBoxOutput.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=241, Height=22}.
        /// </summary>
        public static System.Drawing.Size textBoxOutput_Size {
            get {
                object obj = ResourceManager.GetObject("textBoxOutput.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 15.
        /// </summary>
        public static int textBoxOutput_TabIndex {
            get {
                object obj = ResourceManager.GetObject("textBoxOutput.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string textBoxOutput_ToolTip {
            get {
                return ResourceManager.GetString("textBoxOutput.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk OCR.
        /// </summary>
        public static string this_Title {
            get {
                return ResourceManager.GetString("this.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=186,Y=17}.
        /// </summary>
        public static System.Drawing.Point toolTip1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolTip1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
    }
}
