//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietOCR {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class DownloadDialog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VietOCR.DownloadDialog", typeof(DownloadDialog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        public static bool buttonCancel_Enabled {
            get {
                object obj = ResourceManager.GetObject("buttonCancel.Enabled", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode buttonCancel_ImeMode {
            get {
                object obj = ResourceManager.GetObject("buttonCancel.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=176,Y=54}.
        /// </summary>
        public static System.Drawing.Point buttonCancel_Location {
            get {
                object obj = ResourceManager.GetObject("buttonCancel.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=75, Height=23}.
        /// </summary>
        public static System.Drawing.Size buttonCancel_Size {
            get {
                object obj = ResourceManager.GetObject("buttonCancel.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 6.
        /// </summary>
        public static int buttonCancel_TabIndex {
            get {
                object obj = ResourceManager.GetObject("buttonCancel.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string buttonCancel_Text {
            get {
                return ResourceManager.GetString("buttonCancel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode buttonClose_ImeMode {
            get {
                object obj = ResourceManager.GetObject("buttonClose.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=176,Y=109}.
        /// </summary>
        public static System.Drawing.Point buttonClose_Location {
            get {
                object obj = ResourceManager.GetObject("buttonClose.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=75, Height=23}.
        /// </summary>
        public static System.Drawing.Size buttonClose_Size {
            get {
                object obj = ResourceManager.GetObject("buttonClose.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        public static int buttonClose_TabIndex {
            get {
                object obj = ResourceManager.GetObject("buttonClose.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string buttonClose_Text {
            get {
                return ResourceManager.GetString("buttonClose.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        public static bool buttonDownload_Enabled {
            get {
                object obj = ResourceManager.GetObject("buttonDownload.Enabled", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode buttonDownload_ImeMode {
            get {
                object obj = ResourceManager.GetObject("buttonDownload.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=176,Y=25}.
        /// </summary>
        public static System.Drawing.Point buttonDownload_Location {
            get {
                object obj = ResourceManager.GetObject("buttonDownload.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=75, Height=23}.
        /// </summary>
        public static System.Drawing.Size buttonDownload_Size {
            get {
                object obj = ResourceManager.GetObject("buttonDownload.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        public static int buttonDownload_TabIndex {
            get {
                object obj = ResourceManager.GetObject("buttonDownload.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string buttonDownload_Text {
            get {
                return ResourceManager.GetString("buttonDownload.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=6,Y=6}.
        /// </summary>
        public static System.Drawing.Point groupBox1_Location {
            get {
                object obj = ResourceManager.GetObject("groupBox1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=158, Height=142}.
        /// </summary>
        public static System.Drawing.Size groupBox1_Size {
            get {
                object obj = ResourceManager.GetObject("groupBox1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 7.
        /// </summary>
        public static int groupBox1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("groupBox1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Languages.
        /// </summary>
        public static string groupBox1_Text {
            get {
                return ResourceManager.GetString("groupBox1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=18}.
        /// </summary>
        public static System.Drawing.Point listBox1_Location {
            get {
                object obj = ResourceManager.GetObject("listBox1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=152, Height=121}.
        /// </summary>
        public static System.Drawing.Size listBox1_Size {
            get {
                object obj = ResourceManager.GetObject("listBox1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        public static int listBox1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("listBox1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=158}.
        /// </summary>
        public static System.Drawing.Point statusStrip1_Location {
            get {
                object obj = ResourceManager.GetObject("statusStrip1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=263, Height=22}.
        /// </summary>
        public static System.Drawing.Size statusStrip1_Size {
            get {
                object obj = ResourceManager.GetObject("statusStrip1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 5.
        /// </summary>
        public static int statusStrip1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("statusStrip1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=158}.
        /// </summary>
        public static System.Drawing.Point statusStrip1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("statusStrip1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Language Data.
        /// </summary>
        public static string this_Title {
            get {
                return ResourceManager.GetString("this.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=100, Height=16}.
        /// </summary>
        public static System.Drawing.Size toolStripProgressBar1_Size {
            get {
                object obj = ResourceManager.GetObject("toolStripProgressBar1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        public static bool toolStripProgressBar1_Visible {
            get {
                object obj = ResourceManager.GetObject("toolStripProgressBar1.Visible", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=0, Height=17}.
        /// </summary>
        public static System.Drawing.Size toolStripStatusLabel1_Size {
            get {
                object obj = ResourceManager.GetObject("toolStripStatusLabel1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
    }
}
