//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietOCR {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class FindReplaceDialog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
                
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VietOCR.FindReplaceDialog", typeof(FindReplaceDialog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string btnClose_Text {
            get {
                return ResourceManager.GetString("btnClose.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Find Next.
        /// </summary>
        public static string btnFindNext_Text {
            get {
                return ResourceManager.GetString("btnFindNext.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Replace.
        /// </summary>
        public static string btnReplace_Text {
            get {
                return ResourceManager.GetString("btnReplace.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace _All.
        /// </summary>
        public static string btnReplaceAll_Text {
            get {
                return ResourceManager.GetString("btnReplaceAll.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Ca_se.
        /// </summary>
        public static string chkboxMatchCase_Text {
            get {
                return ResourceManager.GetString("chkboxMatchCase.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match D_iacritics.
        /// </summary>
        public static string chkboxMatchDiacritics_Text {
            get {
                return ResourceManager.GetString("chkboxMatchDiacritics.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular _Expression.
        /// </summary>
        public static string chkboxMatchRegex_Text {
            get {
                return ResourceManager.GetString("chkboxMatchRegex.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match _Whole Word.
        /// </summary>
        public static string chkboxMatchWholeWord_Text {
            get {
                return ResourceManager.GetString("chkboxMatchWholeWord.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        public static string grpboxDirection_Text {
            get {
                return ResourceManager.GetString("grpboxDirection.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find W_hat:.
        /// </summary>
        public static string labelFind_Text {
            get {
                return ResourceManager.GetString("labelFind.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re_place With:.
        /// </summary>
        public static string labelReplace_Text {
            get {
                return ResourceManager.GetString("labelReplace.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search _Down.
        /// </summary>
        public static string radiobtnDown_Text {
            get {
                return ResourceManager.GetString("radiobtnDown.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search _Up.
        /// </summary>
        public static string radiobtnUp_Text {
            get {
                return ResourceManager.GetString("radiobtnUp.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find and Replace.
        /// </summary>
        public static string this_Title {
            get {
                return ResourceManager.GetString("this.Title", resourceCulture);
            }
        }
    }
}
