//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietOCR {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class Gui {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
               
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VietOCR.Gui", typeof(Gui).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About VietOCR.NET.
        /// </summary>
        public static string aboutToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("aboutToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Auto Crop.
        /// </summary>
        public static string autocropToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("autocropToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilate_ral.
        /// </summary>
        public static string bilateralToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("bilateralToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Brightness....
        /// </summary>
        public static string brightenToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("brightenToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Bulk OCR....
        /// </summary>
        public static string bulkOCRToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("bulkOCRToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ».
        /// </summary>
        public static string buttonCollapseExpand_Text {
            get {
                return ResourceManager.GetString("buttonCollapseExpand.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Thumbnails.
        /// </summary>
        public static string buttonCollapseExpand_ToolTip {
            get {
                return ResourceManager.GetString("buttonCollapseExpand.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Change Case....
        /// </summary>
        public static string changeCaseToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("changeCaseToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Command.
        /// </summary>
        public static string commandToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("commandToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Contrast....
        /// </summary>
        public static string contrastToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("contrastToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Convert PDF....
        /// </summary>
        public static string convertPdfToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("convertPdfToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Crop.
        /// </summary>
        public static string cropToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("cropToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Deskew.
        /// </summary>
        public static string deskewToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("deskewToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Speckles.
        /// </summary>
        public static string despeckleToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("despeckleToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Download Language Data....
        /// </summary>
        public static string downloadLangDataToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("downloadLangDataToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string fileToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("fileToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Filters.
        /// </summary>
        public static string filterToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("filterToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Font....
        /// </summary>
        public static string fontToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("fontToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F_ormat.
        /// </summary>
        public static string formatToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("formatToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamm_a....
        /// </summary>
        public static string gammaToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("gammaToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Grayscale.
        /// </summary>
        public static string grayscaleToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("grayscaleToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string helpToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("helpToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VietOCR.NET _Help.
        /// </summary>
        public static string helpToolStripMenuItem1_Text {
            get {
                return ResourceManager.GetString("helpToolStripMenuItem1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Image.
        /// </summary>
        public static string imageToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("imageToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Invert.
        /// </summary>
        public static string invertToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("invertToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menuStrip1.
        /// </summary>
        public static string menuStrip1_Text {
            get {
                return ResourceManager.GetString("menuStrip1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge _PDF....
        /// </summary>
        public static string mergePdfToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("mergePdfToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge _TIFF....
        /// </summary>
        public static string mergeTiffToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("mergeTiffToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Properties....
        /// </summary>
        public static string metadataToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("metadataToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Monochrome.
        /// </summary>
        public static string monochromeToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("monochromeToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR _All Pages.
        /// </summary>
        public static string oCRAllPagesToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("oCRAllPagesToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _OCR.
        /// </summary>
        public static string oCRToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("oCRToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR _Engine Mode.
        /// </summary>
        public static string oemToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("oemToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open....
        /// </summary>
        public static string openToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("openToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Options....
        /// </summary>
        public static string optionsToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("optionsToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Post-process.
        /// </summary>
        public static string postprocessToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("postprocessToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page _Segmentation Mode.
        /// </summary>
        public static string psmToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("psmToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string quitToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("quitToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Recent Files.
        /// </summary>
        public static string recentFilesToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("recentFilesToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Remove Line Breaks.
        /// </summary>
        public static string removeLineBreaksToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("removeLineBreaksToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Remove Lines.
        /// </summary>
        public static string removeLinesToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("removeLinesToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save _As....
        /// </summary>
        public static string saveAsToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("saveAsToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string saveToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("saveToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sca_n....
        /// </summary>
        public static string scanToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("scanToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Screenshot Mode.
        /// </summary>
        public static string screenshotModeToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("screenshotModeToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show S_egmented Regions.
        /// </summary>
        public static string segmentedRegionsToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("segmentedRegionsToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings.
        /// </summary>
        public static string settingsToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("settingsToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Sharpen.
        /// </summary>
        public static string sharpenToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("sharpenToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sm_ooth.
        /// </summary>
        public static string smoothToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("smoothToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Split PDF....
        /// </summary>
        public static string splitPdfToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("splitPdfToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spl_it TIFF....
        /// </summary>
        public static string splitTiffToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("splitTiffToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statusStrip1.
        /// </summary>
        public static string statusStrip1_Text {
            get {
                return ResourceManager.GetString("statusStrip1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Threshold....
        /// </summary>
        public static string thresholdToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("thresholdToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tools.
        /// </summary>
        public static string toolsToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("toolsToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toolStrip1.
        /// </summary>
        public static string toolStrip1_Text {
            get {
                return ResourceManager.GetString("toolStrip1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toolStrip2.
        /// </summary>
        public static string toolStrip2_Text {
            get {
                return ResourceManager.GetString("toolStrip2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap toolStripBtnActualSize_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripBtnActualSize.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Size.
        /// </summary>
        public static string toolStripBtnActualSize_ToolTipText {
            get {
                return ResourceManager.GetString("toolStripBtnActualSize.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap toolStripBtnClear_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripBtnClear.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string toolStripBtnClear_Text {
            get {
                return ResourceManager.GetString("toolStripBtnClear.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Textbox.
        /// </summary>
        public static string toolStripBtnClear_ToolTipText {
            get {
                return ResourceManager.GetString("toolStripBtnClear.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap toolStripBtnFitImage_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripBtnFitImage.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ┼.
        /// </summary>
        public static string toolStripBtnFitImage_Text {
            get {
                return ResourceManager.GetString("toolStripBtnFitImage.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit Image.
        /// </summary>
        public static string toolStripBtnFitImage_ToolTipText {
            get {
                return ResourceManager.GetString("toolStripBtnFitImage.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap toolStripBtnNext_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripBtnNext.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        public static string toolStripBtnNext_Text {
            get {
                return ResourceManager.GetString("toolStripBtnNext.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Page.
        /// </summary>
        public static string toolStripBtnNext_ToolTipText {
            get {
                return ResourceManager.GetString("toolStripBtnNext.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap toolStripBtnOCR_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripBtnOCR.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR.
        /// </summary>
        public static string toolStripBtnOCR_Text {
            get {
                return ResourceManager.GetString("toolStripBtnOCR.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform OCR.
        /// </summary>
        public static string toolStripBtnOCR_ToolTipText {
            get {
                return ResourceManager.GetString("toolStripBtnOCR.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap toolStripBtnOpen_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripBtnOpen.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string toolStripBtnOpen_Text {
            get {
                return ResourceManager.GetString("toolStripBtnOpen.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Image File.
        /// </summary>
        public static string toolStripBtnOpen_ToolTipText {
            get {
                return ResourceManager.GetString("toolStripBtnOpen.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap toolStripBtnPrev_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripBtnPrev.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        public static string toolStripBtnPrev_Text {
            get {
                return ResourceManager.GetString("toolStripBtnPrev.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Page.
        /// </summary>
        public static string toolStripBtnPrev_ToolTipText {
            get {
                return ResourceManager.GetString("toolStripBtnPrev.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap toolStripBtnRotateCCW_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripBtnRotateCCW.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCCW.
        /// </summary>
        public static string toolStripBtnRotateCCW_Text {
            get {
                return ResourceManager.GetString("toolStripBtnRotateCCW.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate Counterclockwise.
        /// </summary>
        public static string toolStripBtnRotateCCW_ToolTipText {
            get {
                return ResourceManager.GetString("toolStripBtnRotateCCW.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap toolStripBtnRotateCW_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripBtnRotateCW.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCW.
        /// </summary>
        public static string toolStripBtnRotateCW_Text {
            get {
                return ResourceManager.GetString("toolStripBtnRotateCW.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate Clockwise.
        /// </summary>
        public static string toolStripBtnRotateCW_ToolTipText {
            get {
                return ResourceManager.GetString("toolStripBtnRotateCW.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap toolStripBtnSave_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripBtnSave.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string toolStripBtnSave_Text {
            get {
                return ResourceManager.GetString("toolStripBtnSave.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Text File.
        /// </summary>
        public static string toolStripBtnSave_ToolTipText {
            get {
                return ResourceManager.GetString("toolStripBtnSave.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap toolStripBtnScan_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripBtnScan.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        public static string toolStripBtnScan_Text {
            get {
                return ResourceManager.GetString("toolStripBtnScan.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Document.
        /// </summary>
        public static string toolStripBtnScan_ToolTipText {
            get {
                return ResourceManager.GetString("toolStripBtnScan.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap toolStripBtnZoomIn_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripBtnZoomIn.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (+).
        /// </summary>
        public static string toolStripBtnZoomIn_Text {
            get {
                return ResourceManager.GetString("toolStripBtnZoomIn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In.
        /// </summary>
        public static string toolStripBtnZoomIn_ToolTipText {
            get {
                return ResourceManager.GetString("toolStripBtnZoomIn.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap toolStripBtnZoomOut_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripBtnZoomOut.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (-).
        /// </summary>
        public static string toolStripBtnZoomOut_Text {
            get {
                return ResourceManager.GetString("toolStripBtnZoomOut.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Out.
        /// </summary>
        public static string toolStripBtnZoomOut_ToolTipText {
            get {
                return ResourceManager.GetString("toolStripBtnZoomOut.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap toolStripButtonCancelOCR_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripButtonCancelOCR.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel OCR.
        /// </summary>
        public static string toolStripButtonCancelOCR_Text {
            get {
                return ResourceManager.GetString("toolStripButtonCancelOCR.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap toolStripButtonPasteImage_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripButtonPasteImage.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Image from Clipboard.
        /// </summary>
        public static string toolStripButtonPasteImage_ToolTipText {
            get {
                return ResourceManager.GetString("toolStripButtonPasteImage.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap toolStripButtonPostProcess_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripButtonPostProcess.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-process.
        /// </summary>
        public static string toolStripButtonPostProcess_ToolTipText {
            get {
                return ResourceManager.GetString("toolStripButtonPostProcess.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap toolStripButtonRemoveLineBreaks_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripButtonRemoveLineBreaks.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Line Breaks.
        /// </summary>
        public static string toolStripButtonRemoveLineBreaks_ToolTipText {
            get {
                return ResourceManager.GetString("toolStripButtonRemoveLineBreaks.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap toolStripButtonSpellCheck_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripButtonSpellCheck.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell Check.
        /// </summary>
        public static string toolStripButtonSpellCheck_ToolTipText {
            get {
                return ResourceManager.GetString("toolStripButtonSpellCheck.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap toolStripDropDownButtonSegmentedRegions_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripDropDownButtonSegmentedRegions.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segmented Regions.
        /// </summary>
        public static string toolStripDropDownButtonSegmentedRegions_Text {
            get {
                return ResourceManager.GetString("toolStripDropDownButtonSegmentedRegions.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segmented Regions.
        /// </summary>
        public static string toolStripDropDownButtonSegmentedRegions_ToolTipText {
            get {
                return ResourceManager.GetString("toolStripDropDownButtonSegmentedRegions.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR Language.
        /// </summary>
        public static string toolStripLabelLanguage_Text {
            get {
                return ResourceManager.GetString("toolStripLabelLanguage.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR Language.
        /// </summary>
        public static string toolStripLabelLanguage_ToolTipText {
            get {
                return ResourceManager.GetString("toolStripLabelLanguage.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  / 0.
        /// </summary>
        public static string toolStripLabelPageNum_Text {
            get {
                return ResourceManager.GetString("toolStripLabelPageNum.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string toolStripMenuItemBlock_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItemBlock.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragraph.
        /// </summary>
        public static string toolStripMenuItemPara_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItemPara.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        public static string toolStripMenuItemSymbol_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItemSymbol.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Line.
        /// </summary>
        public static string toolStripMenuItemTextLine_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItemTextLine.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word.
        /// </summary>
        public static string toolStripMenuItemWord_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItemWord.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image:.
        /// </summary>
        public static string toolStripStatusLabelDim_Text {
            get {
                return ResourceManager.GetString("toolStripStatusLabelDim.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Dimensions &amp; Bit Depth.
        /// </summary>
        public static string toolStripStatusLabelDim_ToolTipText {
            get {
                return ResourceManager.GetString("toolStripStatusLabelDim.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 × 0px  0bpp.
        /// </summary>
        public static string toolStripStatusLabelDimValue_Text {
            get {
                return ResourceManager.GetString("toolStripStatusLabelDimValue.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEM:.
        /// </summary>
        public static string toolStripStatusLabelOEM_Text {
            get {
                return ResourceManager.GetString("toolStripStatusLabelOEM.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR Engine Mode.
        /// </summary>
        public static string toolStripStatusLabelOEM_ToolTipText {
            get {
                return ResourceManager.GetString("toolStripStatusLabelOEM.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSM:.
        /// </summary>
        public static string toolStripStatusLabelPSM_Text {
            get {
                return ResourceManager.GetString("toolStripStatusLabelPSM.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Segmentation Mode.
        /// </summary>
        public static string toolStripStatusLabelPSM_ToolTipText {
            get {
                return ResourceManager.GetString("toolStripStatusLabelPSM.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot Mode:.
        /// </summary>
        public static string toolStripStatusLabelSM_Text {
            get {
                return ResourceManager.GetString("toolStripStatusLabelSM.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot Mode.
        /// </summary>
        public static string toolStripStatusLabelSM_ToolTipText {
            get {
                return ResourceManager.GetString("toolStripStatusLabelSM.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _User Interface Language.
        /// </summary>
        public static string uiLanguageToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("uiLanguageToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Undo.
        /// </summary>
        public static string undoToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("undoToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to 2x2.
        /// </summary>
        public static string upto2x2ToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("upto2x2ToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to 3x3.
        /// </summary>
        public static string upto3x3ToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("upto3x3ToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viet Input _Method.
        /// </summary>
        public static string vietInputMethodToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("vietInputMethodToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Word Wrap.
        /// </summary>
        public static string wordWrapToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("wordWrapToolStripMenuItem.Text", resourceCulture);
            }
        }
    }
}
