//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietOCR {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ImageInfoDialog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VietOCR.ImageInfoDialog", typeof(ImageInfoDialog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=80,Y=160}.
        /// </summary>
        public static System.Drawing.Point buttonOK_Location {
            get {
                object obj = ResourceManager.GetObject("buttonOK.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=75, Height=23}.
        /// </summary>
        public static System.Drawing.Size buttonOK_Size {
            get {
                object obj = ResourceManager.GetObject("buttonOK.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        public static int buttonOK_TabIndex {
            get {
                object obj = ResourceManager.GetObject("buttonOK.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string buttonOK_Text {
            get {
                return ResourceManager.GetString("buttonOK.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pixels.
        /// </summary>
        public static string comboBox3_Items {
            get {
                return ResourceManager.GetString("comboBox3.Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inches.
        /// </summary>
        public static string comboBox3_Items1 {
            get {
                return ResourceManager.GetString("comboBox3.Items1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cm.
        /// </summary>
        public static string comboBox3_Items2 {
            get {
                return ResourceManager.GetString("comboBox3.Items2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=147,Y=19}.
        /// </summary>
        public static System.Drawing.Point comboBox3_Location {
            get {
                object obj = ResourceManager.GetObject("comboBox3.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=60, Height=21}.
        /// </summary>
        public static System.Drawing.Size comboBox3_Size {
            get {
                object obj = ResourceManager.GetObject("comboBox3.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 12.
        /// </summary>
        public static int comboBox3_TabIndex {
            get {
                object obj = ResourceManager.GetObject("comboBox3.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pixels.
        /// </summary>
        public static string comboBox4_Items {
            get {
                return ResourceManager.GetString("comboBox4.Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inches.
        /// </summary>
        public static string comboBox4_Items1 {
            get {
                return ResourceManager.GetString("comboBox4.Items1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cm.
        /// </summary>
        public static string comboBox4_Items2 {
            get {
                return ResourceManager.GetString("comboBox4.Items2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=147,Y=44}.
        /// </summary>
        public static System.Drawing.Point comboBox4_Location {
            get {
                object obj = ResourceManager.GetObject("comboBox4.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=60, Height=21}.
        /// </summary>
        public static System.Drawing.Size comboBox4_Size {
            get {
                object obj = ResourceManager.GetObject("comboBox4.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 13.
        /// </summary>
        public static int comboBox4_TabIndex {
            get {
                object obj = ResourceManager.GetObject("comboBox4.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool label5_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label5.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=145,Y=74}.
        /// </summary>
        public static System.Drawing.Point label5_Location {
            get {
                object obj = ResourceManager.GetObject("label5.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=25, Height=13}.
        /// </summary>
        public static System.Drawing.Size label5_Size {
            get {
                object obj = ResourceManager.GetObject("label5.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 14.
        /// </summary>
        public static int label5_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label5.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPI.
        /// </summary>
        public static string label5_Text {
            get {
                return ResourceManager.GetString("label5.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool label6_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label6.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode label6_ImeMode {
            get {
                object obj = ResourceManager.GetObject("label6.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=145,Y=100}.
        /// </summary>
        public static System.Drawing.Point label6_Location {
            get {
                object obj = ResourceManager.GetObject("label6.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=25, Height=13}.
        /// </summary>
        public static System.Drawing.Size label6_Size {
            get {
                object obj = ResourceManager.GetObject("label6.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 15.
        /// </summary>
        public static int label6_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label6.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPI.
        /// </summary>
        public static string label6_Text {
            get {
                return ResourceManager.GetString("label6.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool labelBitDepth_AutoSize {
            get {
                object obj = ResourceManager.GetObject("labelBitDepth.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode labelBitDepth_ImeMode {
            get {
                object obj = ResourceManager.GetObject("labelBitDepth.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=26,Y=126}.
        /// </summary>
        public static System.Drawing.Point labelBitDepth_Location {
            get {
                object obj = ResourceManager.GetObject("labelBitDepth.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=51, Height=13}.
        /// </summary>
        public static System.Drawing.Size labelBitDepth_Size {
            get {
                object obj = ResourceManager.GetObject("labelBitDepth.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 16.
        /// </summary>
        public static int labelBitDepth_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelBitDepth.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit Depth.
        /// </summary>
        public static string labelBitDepth_Text {
            get {
                return ResourceManager.GetString("labelBitDepth.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool labelHeight_AutoSize {
            get {
                object obj = ResourceManager.GetObject("labelHeight.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=26,Y=48}.
        /// </summary>
        public static System.Drawing.Point labelHeight_Location {
            get {
                object obj = ResourceManager.GetObject("labelHeight.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=38, Height=13}.
        /// </summary>
        public static System.Drawing.Size labelHeight_Size {
            get {
                object obj = ResourceManager.GetObject("labelHeight.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 7.
        /// </summary>
        public static int labelHeight_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelHeight.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string labelHeight_Text {
            get {
                return ResourceManager.GetString("labelHeight.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool labelWidth_AutoSize {
            get {
                object obj = ResourceManager.GetObject("labelWidth.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=26,Y=22}.
        /// </summary>
        public static System.Drawing.Point labelWidth_Location {
            get {
                object obj = ResourceManager.GetObject("labelWidth.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=35, Height=13}.
        /// </summary>
        public static System.Drawing.Size labelWidth_Size {
            get {
                object obj = ResourceManager.GetObject("labelWidth.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 5.
        /// </summary>
        public static int labelWidth_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelWidth.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string labelWidth_Text {
            get {
                return ResourceManager.GetString("labelWidth.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool labelXRes_AutoSize {
            get {
                object obj = ResourceManager.GetObject("labelXRes.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=26,Y=74}.
        /// </summary>
        public static System.Drawing.Point labelXRes_Location {
            get {
                object obj = ResourceManager.GetObject("labelXRes.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=67, Height=13}.
        /// </summary>
        public static System.Drawing.Size labelXRes_Size {
            get {
                object obj = ResourceManager.GetObject("labelXRes.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        public static int labelXRes_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelXRes.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-Resolution.
        /// </summary>
        public static string labelXRes_Text {
            get {
                return ResourceManager.GetString("labelXRes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool labelYRes_AutoSize {
            get {
                object obj = ResourceManager.GetObject("labelYRes.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=26,Y=100}.
        /// </summary>
        public static System.Drawing.Point labelYRes_Location {
            get {
                object obj = ResourceManager.GetObject("labelYRes.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=67, Height=13}.
        /// </summary>
        public static System.Drawing.Size labelYRes_Size {
            get {
                object obj = ResourceManager.GetObject("labelYRes.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 3.
        /// </summary>
        public static int labelYRes_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelYRes.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y-Resolution.
        /// </summary>
        public static string labelYRes_Text {
            get {
                return ResourceManager.GetString("labelYRes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=96,Y=123}.
        /// </summary>
        public static System.Drawing.Point textBoxBitDepth_Location {
            get {
                object obj = ResourceManager.GetObject("textBoxBitDepth.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=45, Height=20}.
        /// </summary>
        public static System.Drawing.Size textBoxBitDepth_Size {
            get {
                object obj = ResourceManager.GetObject("textBoxBitDepth.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 17.
        /// </summary>
        public static int textBoxBitDepth_TabIndex {
            get {
                object obj = ResourceManager.GetObject("textBoxBitDepth.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=96,Y=45}.
        /// </summary>
        public static System.Drawing.Point textBoxHeight_Location {
            get {
                object obj = ResourceManager.GetObject("textBoxHeight.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=45, Height=20}.
        /// </summary>
        public static System.Drawing.Size textBoxHeight_Size {
            get {
                object obj = ResourceManager.GetObject("textBoxHeight.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 8.
        /// </summary>
        public static int textBoxHeight_TabIndex {
            get {
                object obj = ResourceManager.GetObject("textBoxHeight.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=96,Y=19}.
        /// </summary>
        public static System.Drawing.Point textBoxWidth_Location {
            get {
                object obj = ResourceManager.GetObject("textBoxWidth.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=45, Height=20}.
        /// </summary>
        public static System.Drawing.Size textBoxWidth_Size {
            get {
                object obj = ResourceManager.GetObject("textBoxWidth.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 6.
        /// </summary>
        public static int textBoxWidth_TabIndex {
            get {
                object obj = ResourceManager.GetObject("textBoxWidth.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=96,Y=71}.
        /// </summary>
        public static System.Drawing.Point textBoxXRes_Location {
            get {
                object obj = ResourceManager.GetObject("textBoxXRes.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=45, Height=20}.
        /// </summary>
        public static System.Drawing.Size textBoxXRes_Size {
            get {
                object obj = ResourceManager.GetObject("textBoxXRes.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        public static int textBoxXRes_TabIndex {
            get {
                object obj = ResourceManager.GetObject("textBoxXRes.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=96,Y=97}.
        /// </summary>
        public static System.Drawing.Point textBoxYRes_Location {
            get {
                object obj = ResourceManager.GetObject("textBoxYRes.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=45, Height=20}.
        /// </summary>
        public static System.Drawing.Size textBoxYRes_Size {
            get {
                object obj = ResourceManager.GetObject("textBoxYRes.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 4.
        /// </summary>
        public static int textBoxYRes_TabIndex {
            get {
                object obj = ResourceManager.GetObject("textBoxYRes.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Properties.
        /// </summary>
        public static string this_Title {
            get {
                return ResourceManager.GetString("this.Title", resourceCulture);
            }
        }
    }
}
