//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietOCR {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class OptionsDialog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
               
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VietOCR.OptionsDialog", typeof(OptionsDialog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch.
        /// </summary>
        public static string Batch {
            get {
                return ResourceManager.GetString("Batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string btnDangAmbigs_Text {
            get {
                return ResourceManager.GetString("btnDangAmbigs.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string btnDangAmbigs_ToolTip {
            get {
                return ResourceManager.GetString("btnDangAmbigs.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string btnOutput_Text {
            get {
                return ResourceManager.GetString("btnOutput.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string btnOutput_ToolTip {
            get {
                return ResourceManager.GetString("btnOutput.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string btnWatch_Text {
            get {
                return ResourceManager.GetString("btnWatch.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string btnWatch_ToolTip {
            get {
                return ResourceManager.GetString("btnWatch.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk/Batch Options.
        /// </summary>
        public static string BulkBatchOptions {
            get {
                return ResourceManager.GetString("BulkBatchOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string buttonCancel_Text {
            get {
                return ResourceManager.GetString("buttonCancel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string buttonCancel_ToolTip {
            get {
                return ResourceManager.GetString("buttonCancel.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string buttonOK_Text {
            get {
                return ResourceManager.GetString("buttonOK.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string buttonOK_ToolTip {
            get {
                return ResourceManager.GetString("buttonOK.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct Letter Cases.
        /// </summary>
        public static string checkBoxCorrectLetterCases_Text {
            get {
                return ResourceManager.GetString("checkBoxCorrectLetterCases.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string checkBoxDangAmbigs_Text {
            get {
                return ResourceManager.GetString("checkBoxDangAmbigs.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string checkBoxDangAmbigs_ToolTip {
            get {
                return ResourceManager.GetString("checkBoxDangAmbigs.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deskew.
        /// </summary>
        public static string checkBoxDeskew_Text {
            get {
                return ResourceManager.GetString("checkBoxDeskew.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Processing.
        /// </summary>
        public static string checkBoxPostProcessing_Text {
            get {
                return ResourceManager.GetString("checkBoxPostProcessing.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove soft hyphens.
        /// </summary>
        public static string checkBoxRemoveHyphens_Text {
            get {
                return ResourceManager.GetString("checkBoxRemoveHyphens.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove soft hyphens after removing line breaks.
        /// </summary>
        public static string checkBoxRemoveHyphens_ToolTip {
            get {
                return ResourceManager.GetString("checkBoxRemoveHyphens.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Line Breaks.
        /// </summary>
        public static string checkBoxRemoveLineBreaks_Text {
            get {
                return ResourceManager.GetString("checkBoxRemoveLineBreaks.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Lines.
        /// </summary>
        public static string checkBoxRemoveLines_Text {
            get {
                return ResourceManager.GetString("checkBoxRemoveLines.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace hyphens with soft hyphens.
        /// </summary>
        public static string checkBoxReplaceHyphens_Text {
            get {
                return ResourceManager.GetString("checkBoxReplaceHyphens.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace hyphens at the end of lines with soft hyphens using spellcheck dictionary.
        /// </summary>
        public static string checkBoxReplaceHyphens_ToolTip {
            get {
                return ResourceManager.GetString("checkBoxReplaceHyphens.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text-only PDF.
        /// </summary>
        public static string checkBoxTextOnlyPdf_Text {
            get {
                return ResourceManager.GetString("checkBoxTextOnlyPdf.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string checkBoxWatch_Text {
            get {
                return ResourceManager.GetString("checkBoxWatch.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string checkBoxWatch_ToolTip {
            get {
                return ResourceManager.GetString("checkBoxWatch.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string comboBoxOutputFormat_ToolTip {
            get {
                return ResourceManager.GetString("comboBoxOutputFormat.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyphens.
        /// </summary>
        public static string Hyphens {
            get {
                return ResourceManager.GetString("Hyphens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Folder:.
        /// </summary>
        public static string labelOutput_Text {
            get {
                return ResourceManager.GetString("labelOutput.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string labelOutput_ToolTip {
            get {
                return ResourceManager.GetString("labelOutput.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Format.
        /// </summary>
        public static string labelOutputFormat_Text {
            get {
                return ResourceManager.GetString("labelOutputFormat.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string labelOutputFormat_ToolTip {
            get {
                return ResourceManager.GetString("labelOutputFormat.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path:.
        /// </summary>
        public static string labelPath_Text {
            get {
                return ResourceManager.GetString("labelPath.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string labelPath_ToolTip {
            get {
                return ResourceManager.GetString("labelPath.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch Folder:.
        /// </summary>
        public static string labelWatch_Text {
            get {
                return ResourceManager.GetString("labelWatch.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string labelWatch_ToolTip {
            get {
                return ResourceManager.GetString("labelWatch.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Files (*.txt)|*.txt.
        /// </summary>
        public static string openFileDialog1_Filter {
            get {
                return ResourceManager.GetString("openFileDialog1.Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an output format..
        /// </summary>
        public static string Please_select_output_format {
            get {
                return ResourceManager.GetString("Please_select_output_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string tabControl1_ToolTip {
            get {
                return ResourceManager.GetString("tabControl1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch.
        /// </summary>
        public static string tabPage1_Text {
            get {
                return ResourceManager.GetString("tabPage1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string tabPage1_ToolTip {
            get {
                return ResourceManager.GetString("tabPage1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DangAmbigs.txt.
        /// </summary>
        public static string tabPage2_Text {
            get {
                return ResourceManager.GetString("tabPage2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string tabPage2_ToolTip {
            get {
                return ResourceManager.GetString("tabPage2.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyphens.
        /// </summary>
        public static string tabPage3_Text {
            get {
                return ResourceManager.GetString("tabPage3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string tabPage3_ToolTip {
            get {
                return ResourceManager.GetString("tabPage3.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string textBoxDangAmbigs_ToolTip {
            get {
                return ResourceManager.GetString("textBoxDangAmbigs.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string textBoxOutput_ToolTip {
            get {
                return ResourceManager.GetString("textBoxOutput.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string textBoxWatch_ToolTip {
            get {
                return ResourceManager.GetString("textBoxWatch.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string this_Title {
            get {
                return ResourceManager.GetString("this.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch.
        /// </summary>
        public static string Watch {
            get {
                return ResourceManager.GetString("Watch", resourceCulture);
            }
        }
    }
}
