//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietOCR {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class OptionsDialog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VietOCR.OptionsDialog", typeof(OptionsDialog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode btnDangAmbigs_ImeMode {
            get {
                object obj = ResourceManager.GetObject("btnDangAmbigs.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=355,Y=16}.
        /// </summary>
        public static System.Drawing.Point btnDangAmbigs_Location {
            get {
                object obj = ResourceManager.GetObject("btnDangAmbigs.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        public static System.Windows.Forms.Padding btnDangAmbigs_Margin {
            get {
                object obj = ResourceManager.GetObject("btnDangAmbigs.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=40, Height=28}.
        /// </summary>
        public static System.Drawing.Size btnDangAmbigs_Size {
            get {
                object obj = ResourceManager.GetObject("btnDangAmbigs.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 16.
        /// </summary>
        public static int btnDangAmbigs_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnDangAmbigs.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string btnDangAmbigs_Text {
            get {
                return ResourceManager.GetString("btnDangAmbigs.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string btnDangAmbigs_ToolTip {
            get {
                return ResourceManager.GetString("btnDangAmbigs.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode btnOutput_ImeMode {
            get {
                object obj = ResourceManager.GetObject("btnOutput.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=355,Y=46}.
        /// </summary>
        public static System.Drawing.Point btnOutput_Location {
            get {
                object obj = ResourceManager.GetObject("btnOutput.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        public static System.Windows.Forms.Padding btnOutput_Margin {
            get {
                object obj = ResourceManager.GetObject("btnOutput.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=40, Height=28}.
        /// </summary>
        public static System.Drawing.Size btnOutput_Size {
            get {
                object obj = ResourceManager.GetObject("btnOutput.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 11.
        /// </summary>
        public static int btnOutput_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnOutput.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string btnOutput_Text {
            get {
                return ResourceManager.GetString("btnOutput.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string btnOutput_ToolTip {
            get {
                return ResourceManager.GetString("btnOutput.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode btnWatch_ImeMode {
            get {
                object obj = ResourceManager.GetObject("btnWatch.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=355,Y=14}.
        /// </summary>
        public static System.Drawing.Point btnWatch_Location {
            get {
                object obj = ResourceManager.GetObject("btnWatch.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        public static System.Windows.Forms.Padding btnWatch_Margin {
            get {
                object obj = ResourceManager.GetObject("btnWatch.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=40, Height=28}.
        /// </summary>
        public static System.Drawing.Size btnWatch_Size {
            get {
                object obj = ResourceManager.GetObject("btnWatch.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 10.
        /// </summary>
        public static int btnWatch_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnWatch.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string btnWatch_Text {
            get {
                return ResourceManager.GetString("btnWatch.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string btnWatch_ToolTip {
            get {
                return ResourceManager.GetString("btnWatch.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=300,Y=167}.
        /// </summary>
        public static System.Drawing.Point buttonCancel_Location {
            get {
                object obj = ResourceManager.GetObject("buttonCancel.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        public static System.Windows.Forms.Padding buttonCancel_Margin {
            get {
                object obj = ResourceManager.GetObject("buttonCancel.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=100, Height=28}.
        /// </summary>
        public static System.Drawing.Size buttonCancel_Size {
            get {
                object obj = ResourceManager.GetObject("buttonCancel.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        public static int buttonCancel_TabIndex {
            get {
                object obj = ResourceManager.GetObject("buttonCancel.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string buttonCancel_Text {
            get {
                return ResourceManager.GetString("buttonCancel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string buttonCancel_ToolTip {
            get {
                return ResourceManager.GetString("buttonCancel.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=192,Y=167}.
        /// </summary>
        public static System.Drawing.Point buttonOK_Location {
            get {
                object obj = ResourceManager.GetObject("buttonOK.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        public static System.Windows.Forms.Padding buttonOK_Margin {
            get {
                object obj = ResourceManager.GetObject("buttonOK.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=100, Height=28}.
        /// </summary>
        public static System.Drawing.Size buttonOK_Size {
            get {
                object obj = ResourceManager.GetObject("buttonOK.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        public static int buttonOK_TabIndex {
            get {
                object obj = ResourceManager.GetObject("buttonOK.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string buttonOK_Text {
            get {
                return ResourceManager.GetString("buttonOK.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string buttonOK_ToolTip {
            get {
                return ResourceManager.GetString("buttonOK.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool checkBoxDangAmbigs_AutoSize {
            get {
                object obj = ResourceManager.GetObject("checkBoxDangAmbigs.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode checkBoxDangAmbigs_ImeMode {
            get {
                object obj = ResourceManager.GetObject("checkBoxDangAmbigs.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=104,Y=63}.
        /// </summary>
        public static System.Drawing.Point checkBoxDangAmbigs_Location {
            get {
                object obj = ResourceManager.GetObject("checkBoxDangAmbigs.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        public static System.Windows.Forms.Padding checkBoxDangAmbigs_Margin {
            get {
                object obj = ResourceManager.GetObject("checkBoxDangAmbigs.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=74, Height=21}.
        /// </summary>
        public static System.Drawing.Size checkBoxDangAmbigs_Size {
            get {
                object obj = ResourceManager.GetObject("checkBoxDangAmbigs.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 18.
        /// </summary>
        public static int checkBoxDangAmbigs_TabIndex {
            get {
                object obj = ResourceManager.GetObject("checkBoxDangAmbigs.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string checkBoxDangAmbigs_Text {
            get {
                return ResourceManager.GetString("checkBoxDangAmbigs.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string checkBoxDangAmbigs_ToolTip {
            get {
                return ResourceManager.GetString("checkBoxDangAmbigs.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deskew.
        /// </summary>
        public static string checkBoxDeskew_Text {
            get {
                return ResourceManager.GetString("checkBoxDeskew.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove soft hyphens.
        /// </summary>
        public static string checkBoxRemoveHyphens_Text {
            get {
                return ResourceManager.GetString("checkBoxRemoveHyphens.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace hyphens with soft hyphens.
        /// </summary>
        public static string checkBoxReplaceHyphens_Text {
            get {
                return ResourceManager.GetString("checkBoxReplaceHyphens.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool checkBoxWatch_AutoSize {
            get {
                object obj = ResourceManager.GetObject("checkBoxWatch.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode checkBoxWatch_ImeMode {
            get {
                object obj = ResourceManager.GetObject("checkBoxWatch.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=268,Y=91}.
        /// </summary>
        public static System.Drawing.Point checkBoxWatch_Location {
            get {
                object obj = ResourceManager.GetObject("checkBoxWatch.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        public static System.Windows.Forms.Padding checkBoxWatch_Margin {
            get {
                object obj = ResourceManager.GetObject("checkBoxWatch.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=74, Height=21}.
        /// </summary>
        public static System.Drawing.Size checkBoxWatch_Size {
            get {
                object obj = ResourceManager.GetObject("checkBoxWatch.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 14.
        /// </summary>
        public static int checkBoxWatch_TabIndex {
            get {
                object obj = ResourceManager.GetObject("checkBoxWatch.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string checkBoxWatch_Text {
            get {
                return ResourceManager.GetString("checkBoxWatch.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string checkBoxWatch_ToolTip {
            get {
                return ResourceManager.GetString("checkBoxWatch.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text.
        /// </summary>
        public static string comboBoxOutputFormat_Items {
            get {
                return ResourceManager.GetString("comboBoxOutputFormat.Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text+.
        /// </summary>
        public static string comboBoxOutputFormat_Items1 {
            get {
                return ResourceManager.GetString("comboBoxOutputFormat.Items1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hocr.
        /// </summary>
        public static string comboBoxOutputFormat_Items2 {
            get {
                return ResourceManager.GetString("comboBoxOutputFormat.Items2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=105,Y=86}.
        /// </summary>
        public static System.Drawing.Point comboBoxOutputFormat_Location {
            get {
                object obj = ResourceManager.GetObject("comboBoxOutputFormat.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        public static System.Windows.Forms.Padding comboBoxOutputFormat_Margin {
            get {
                object obj = ResourceManager.GetObject("comboBoxOutputFormat.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=64, Height=24}.
        /// </summary>
        public static System.Drawing.Size comboBoxOutputFormat_Size {
            get {
                object obj = ResourceManager.GetObject("comboBoxOutputFormat.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 15.
        /// </summary>
        public static int comboBoxOutputFormat_TabIndex {
            get {
                object obj = ResourceManager.GetObject("comboBoxOutputFormat.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string comboBoxOutputFormat_ToolTip {
            get {
                return ResourceManager.GetString("comboBoxOutputFormat.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=17}.
        /// </summary>
        public static System.Drawing.Point folderBrowserDialog1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("folderBrowserDialog1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool labelOutput_AutoSize {
            get {
                object obj = ResourceManager.GetObject("labelOutput.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode labelOutput_ImeMode {
            get {
                object obj = ResourceManager.GetObject("labelOutput.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=4,Y=52}.
        /// </summary>
        public static System.Drawing.Point labelOutput_Location {
            get {
                object obj = ResourceManager.GetObject("labelOutput.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=0,Right=4,Bottom=0}.
        /// </summary>
        public static System.Windows.Forms.Padding labelOutput_Margin {
            get {
                object obj = ResourceManager.GetObject("labelOutput.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=99, Height=17}.
        /// </summary>
        public static System.Drawing.Size labelOutput_Size {
            get {
                object obj = ResourceManager.GetObject("labelOutput.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 13.
        /// </summary>
        public static int labelOutput_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelOutput.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Folder:.
        /// </summary>
        public static string labelOutput_Text {
            get {
                return ResourceManager.GetString("labelOutput.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string labelOutput_ToolTip {
            get {
                return ResourceManager.GetString("labelOutput.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool labelOutputFormat_AutoSize {
            get {
                object obj = ResourceManager.GetObject("labelOutputFormat.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=4,Y=92}.
        /// </summary>
        public static System.Drawing.Point labelOutputFormat_Location {
            get {
                object obj = ResourceManager.GetObject("labelOutputFormat.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=0,Right=4,Bottom=0}.
        /// </summary>
        public static System.Windows.Forms.Padding labelOutputFormat_Margin {
            get {
                object obj = ResourceManager.GetObject("labelOutputFormat.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=99, Height=17}.
        /// </summary>
        public static System.Drawing.Size labelOutputFormat_Size {
            get {
                object obj = ResourceManager.GetObject("labelOutputFormat.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 16.
        /// </summary>
        public static int labelOutputFormat_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelOutputFormat.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Format.
        /// </summary>
        public static string labelOutputFormat_Text {
            get {
                return ResourceManager.GetString("labelOutputFormat.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string labelOutputFormat_ToolTip {
            get {
                return ResourceManager.GetString("labelOutputFormat.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool labelPath_AutoSize {
            get {
                object obj = ResourceManager.GetObject("labelPath.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode labelPath_ImeMode {
            get {
                object obj = ResourceManager.GetObject("labelPath.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=4,Y=22}.
        /// </summary>
        public static System.Drawing.Point labelPath_Location {
            get {
                object obj = ResourceManager.GetObject("labelPath.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=0,Right=4,Bottom=0}.
        /// </summary>
        public static System.Windows.Forms.Padding labelPath_Margin {
            get {
                object obj = ResourceManager.GetObject("labelPath.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=41, Height=17}.
        /// </summary>
        public static System.Drawing.Size labelPath_Size {
            get {
                object obj = ResourceManager.GetObject("labelPath.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 17.
        /// </summary>
        public static int labelPath_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelPath.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path:.
        /// </summary>
        public static string labelPath_Text {
            get {
                return ResourceManager.GetString("labelPath.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string labelPath_ToolTip {
            get {
                return ResourceManager.GetString("labelPath.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool labelWatch_AutoSize {
            get {
                object obj = ResourceManager.GetObject("labelWatch.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode labelWatch_ImeMode {
            get {
                object obj = ResourceManager.GetObject("labelWatch.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=4,Y=20}.
        /// </summary>
        public static System.Drawing.Point labelWatch_Location {
            get {
                object obj = ResourceManager.GetObject("labelWatch.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=0,Right=4,Bottom=0}.
        /// </summary>
        public static System.Windows.Forms.Padding labelWatch_Margin {
            get {
                object obj = ResourceManager.GetObject("labelWatch.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=96, Height=17}.
        /// </summary>
        public static System.Drawing.Size labelWatch_Size {
            get {
                object obj = ResourceManager.GetObject("labelWatch.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 12.
        /// </summary>
        public static int labelWatch_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelWatch.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch Folder:.
        /// </summary>
        public static string labelWatch_Text {
            get {
                return ResourceManager.GetString("labelWatch.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string labelWatch_ToolTip {
            get {
                return ResourceManager.GetString("labelWatch.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Files (*.txt)|*.txt.
        /// </summary>
        public static string openFileDialog1_Filter {
            get {
                return ResourceManager.GetString("openFileDialog1.Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=186,Y=17}.
        /// </summary>
        public static System.Drawing.Point openFileDialog1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("openFileDialog1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Top.
        /// </summary>
        public static System.Windows.Forms.DockStyle tabControl1_Dock {
            get {
                object obj = ResourceManager.GetObject("tabControl1.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=0}.
        /// </summary>
        public static System.Drawing.Point tabControl1_Location {
            get {
                object obj = ResourceManager.GetObject("tabControl1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        public static System.Windows.Forms.Padding tabControl1_Margin {
            get {
                object obj = ResourceManager.GetObject("tabControl1.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=416, Height=158}.
        /// </summary>
        public static System.Drawing.Size tabControl1_Size {
            get {
                object obj = ResourceManager.GetObject("tabControl1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        public static int tabControl1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tabControl1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string tabControl1_ToolTip {
            get {
                return ResourceManager.GetString("tabControl1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=4,Y=25}.
        /// </summary>
        public static System.Drawing.Point tabPage1_Location {
            get {
                object obj = ResourceManager.GetObject("tabPage1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        public static System.Windows.Forms.Padding tabPage1_Margin {
            get {
                object obj = ResourceManager.GetObject("tabPage1.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        public static System.Windows.Forms.Padding tabPage1_Padding {
            get {
                object obj = ResourceManager.GetObject("tabPage1.Padding", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=408, Height=129}.
        /// </summary>
        public static System.Drawing.Size tabPage1_Size {
            get {
                object obj = ResourceManager.GetObject("tabPage1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        public static int tabPage1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tabPage1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch.
        /// </summary>
        public static string tabPage1_Text {
            get {
                return ResourceManager.GetString("tabPage1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string tabPage1_ToolTip {
            get {
                return ResourceManager.GetString("tabPage1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=4,Y=25}.
        /// </summary>
        public static System.Drawing.Point tabPage2_Location {
            get {
                object obj = ResourceManager.GetObject("tabPage2.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        public static System.Windows.Forms.Padding tabPage2_Margin {
            get {
                object obj = ResourceManager.GetObject("tabPage2.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        public static System.Windows.Forms.Padding tabPage2_Padding {
            get {
                object obj = ResourceManager.GetObject("tabPage2.Padding", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=408, Height=129}.
        /// </summary>
        public static System.Drawing.Size tabPage2_Size {
            get {
                object obj = ResourceManager.GetObject("tabPage2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        public static int tabPage2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tabPage2.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DangAmbigs.txt.
        /// </summary>
        public static string tabPage2_Text {
            get {
                return ResourceManager.GetString("tabPage2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string tabPage2_ToolTip {
            get {
                return ResourceManager.GetString("tabPage2.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyphens.
        /// </summary>
        public static string tabPage3_Text {
            get {
                return ResourceManager.GetString("tabPage3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string tabPage3_ToolTip {
            get {
                return ResourceManager.GetString("tabPage3.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=104,Y=18}.
        /// </summary>
        public static System.Drawing.Point textBoxDangAmbigs_Location {
            get {
                object obj = ResourceManager.GetObject("textBoxDangAmbigs.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        public static System.Windows.Forms.Padding textBoxDangAmbigs_Margin {
            get {
                object obj = ResourceManager.GetObject("textBoxDangAmbigs.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=241, Height=22}.
        /// </summary>
        public static System.Drawing.Size textBoxDangAmbigs_Size {
            get {
                object obj = ResourceManager.GetObject("textBoxDangAmbigs.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 15.
        /// </summary>
        public static int textBoxDangAmbigs_TabIndex {
            get {
                object obj = ResourceManager.GetObject("textBoxDangAmbigs.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string textBoxDangAmbigs_ToolTip {
            get {
                return ResourceManager.GetString("textBoxDangAmbigs.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=104,Y=48}.
        /// </summary>
        public static System.Drawing.Point textBoxOutput_Location {
            get {
                object obj = ResourceManager.GetObject("textBoxOutput.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        public static System.Windows.Forms.Padding textBoxOutput_Margin {
            get {
                object obj = ResourceManager.GetObject("textBoxOutput.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=241, Height=22}.
        /// </summary>
        public static System.Drawing.Size textBoxOutput_Size {
            get {
                object obj = ResourceManager.GetObject("textBoxOutput.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 9.
        /// </summary>
        public static int textBoxOutput_TabIndex {
            get {
                object obj = ResourceManager.GetObject("textBoxOutput.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string textBoxOutput_ToolTip {
            get {
                return ResourceManager.GetString("textBoxOutput.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=104,Y=16}.
        /// </summary>
        public static System.Drawing.Point textBoxWatch_Location {
            get {
                object obj = ResourceManager.GetObject("textBoxWatch.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        public static System.Windows.Forms.Padding textBoxWatch_Margin {
            get {
                object obj = ResourceManager.GetObject("textBoxWatch.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=241, Height=22}.
        /// </summary>
        public static System.Drawing.Size textBoxWatch_Size {
            get {
                object obj = ResourceManager.GetObject("textBoxWatch.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 8.
        /// </summary>
        public static int textBoxWatch_TabIndex {
            get {
                object obj = ResourceManager.GetObject("textBoxWatch.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string textBoxWatch_ToolTip {
            get {
                return ResourceManager.GetString("textBoxWatch.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string this_Title {
            get {
                return ResourceManager.GetString("this.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=326,Y=17}.
        /// </summary>
        public static System.Drawing.Point toolTip1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolTip1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
    }
}
