//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietOCR {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class SplitPdfDialog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
               
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VietOCR.SplitPdfDialog", typeof(SplitPdfDialog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 12.
        /// </summary>
        public static int buttonBrowseInput_TabIndex {
            get {
                object obj = ResourceManager.GetObject("buttonBrowseInput.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string buttonBrowseInput_Text {
            get {
                return ResourceManager.GetString("buttonBrowseInput.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string buttonBrowseInput_ToolTip {
            get {
                return ResourceManager.GetString("buttonBrowseInput.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 13.
        /// </summary>
        public static int buttonBrowseOutput_TabIndex {
            get {
                object obj = ResourceManager.GetObject("buttonBrowseOutput.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string buttonBrowseOutput_Text {
            get {
                return ResourceManager.GetString("buttonBrowseOutput.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string buttonBrowseOutput_ToolTip {
            get {
                return ResourceManager.GetString("buttonBrowseOutput.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        public static int buttonCancel_TabIndex {
            get {
                object obj = ResourceManager.GetObject("buttonCancel.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string buttonCancel_Text {
            get {
                return ResourceManager.GetString("buttonCancel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string buttonCancel_ToolTip {
            get {
                return ResourceManager.GetString("buttonCancel.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        public static int buttonSplit_TabIndex {
            get {
                object obj = ResourceManager.GetObject("buttonSplit.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split.
        /// </summary>
        public static string buttonSplit_Text {
            get {
                return ResourceManager.GetString("buttonSplit.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string buttonSplit_ToolTip {
            get {
                return ResourceManager.GetString("buttonSplit.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool labelFrom_AutoSize {
            get {
                object obj = ResourceManager.GetObject("labelFrom.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 5.
        /// </summary>
        public static int labelFrom_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelFrom.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from:.
        /// </summary>
        public static string labelFrom_Text {
            get {
                return ResourceManager.GetString("labelFrom.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string labelFrom_ToolTip {
            get {
                return ResourceManager.GetString("labelFrom.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool labelInput_AutoSize {
            get {
                object obj = ResourceManager.GetObject("labelInput.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 14.
        /// </summary>
        public static int labelInput_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelInput.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input:.
        /// </summary>
        public static string labelInput_Text {
            get {
                return ResourceManager.GetString("labelInput.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string labelInput_ToolTip {
            get {
                return ResourceManager.GetString("labelInput.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool labelNumOfPages_AutoSize {
            get {
                object obj = ResourceManager.GetObject("labelNumOfPages.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 9.
        /// </summary>
        public static int labelNumOfPages_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelNumOfPages.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of pages per file:.
        /// </summary>
        public static string labelNumOfPages_Text {
            get {
                return ResourceManager.GetString("labelNumOfPages.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string labelNumOfPages_ToolTip {
            get {
                return ResourceManager.GetString("labelNumOfPages.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool labelOutput_AutoSize {
            get {
                object obj = ResourceManager.GetObject("labelOutput.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 15.
        /// </summary>
        public static int labelOutput_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelOutput.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output:.
        /// </summary>
        public static string labelOutput_Text {
            get {
                return ResourceManager.GetString("labelOutput.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string labelOutput_ToolTip {
            get {
                return ResourceManager.GetString("labelOutput.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool labelTo_AutoSize {
            get {
                object obj = ResourceManager.GetObject("labelTo.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 6.
        /// </summary>
        public static int labelTo_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelTo.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to:.
        /// </summary>
        public static string labelTo_Text {
            get {
                return ResourceManager.GetString("labelTo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string labelTo_ToolTip {
            get {
                return ResourceManager.GetString("labelTo.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool radioButtonFiles_AutoSize {
            get {
                object obj = ResourceManager.GetObject("radioButtonFiles.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 7.
        /// </summary>
        public static int radioButtonFiles_TabIndex {
            get {
                object obj = ResourceManager.GetObject("radioButtonFiles.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string radioButtonFiles_Text {
            get {
                return ResourceManager.GetString("radioButtonFiles.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string radioButtonFiles_ToolTip {
            get {
                return ResourceManager.GetString("radioButtonFiles.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool radioButtonPages_AutoSize {
            get {
                object obj = ResourceManager.GetObject("radioButtonPages.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 4.
        /// </summary>
        public static int radioButtonPages_TabIndex {
            get {
                object obj = ResourceManager.GetObject("radioButtonPages.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string radioButtonPages_Text {
            get {
                return ResourceManager.GetString("radioButtonPages.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string radioButtonPages_ToolTip {
            get {
                return ResourceManager.GetString("radioButtonPages.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        public static int textBoxFrom_TabIndex {
            get {
                object obj = ResourceManager.GetObject("textBoxFrom.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string textBoxFrom_ToolTip {
            get {
                return ResourceManager.GetString("textBoxFrom.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 10.
        /// </summary>
        public static int textBoxInput_TabIndex {
            get {
                object obj = ResourceManager.GetObject("textBoxInput.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string textBoxInput_ToolTip {
            get {
                return ResourceManager.GetString("textBoxInput.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 8.
        /// </summary>
        public static int textBoxNumOfPages_TabIndex {
            get {
                object obj = ResourceManager.GetObject("textBoxNumOfPages.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        public static string textBoxNumOfPages_Text {
            get {
                return ResourceManager.GetString("textBoxNumOfPages.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string textBoxNumOfPages_ToolTip {
            get {
                return ResourceManager.GetString("textBoxNumOfPages.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 11.
        /// </summary>
        public static int textBoxOutput_TabIndex {
            get {
                object obj = ResourceManager.GetObject("textBoxOutput.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string textBoxOutput_ToolTip {
            get {
                return ResourceManager.GetString("textBoxOutput.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 3.
        /// </summary>
        public static int textBoxTo_TabIndex {
            get {
                object obj = ResourceManager.GetObject("textBoxTo.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string textBoxTo_ToolTip {
            get {
                return ResourceManager.GetString("textBoxTo.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split PDF.
        /// </summary>
        public static string this_Title {
            get {
                return ResourceManager.GetString("this.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string this_ToolTip {
            get {
                return ResourceManager.GetString("this.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=17}.
        /// </summary>
        public static System.Drawing.Point toolTip1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolTip1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
    }
}
